dist: trusty
language: rust
cache: cargo
rust:  
  - stable

matrix: 
  fast_finish: true

before_install:
  - echo "deb http://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_9.0/ ./" >> /etc/apt/sources.list
  - wget https://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_9.0/Release.key -O- | sudo apt-key add
  - sudo apt-get install libzmq3-dev

script:
  - cd aion
  - cargo build --all --release
  - cargo test --verbose --all --release
