dist: trusty
language: rust
cache: cargo
rust:  
  - stable

matrix: 
  fast_finish: true

before_install:
  - sudo apt-get install libzmq-dev

script:
  - cd aion
  - cargo build --all --release
  - cargo test --verbose --all --release
