[package]
name = "aion"
version = "0.1.0"
authors = ["olaf <o_van_wijk@hotmail.com>"]

[dependencies]
zmq = "0.9.1"
actix-web = "1.0.7"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
json = "*"
